# Replacing User Latent Vector With Behavioural Sequence RNN Output For CF Recommendation

##### For the situations that we * don't have fresh user embedding* 

#### Good side of user embedding
The latent space empowers the model to featurize the characters of user, entirely by learning.
#### Bad side of user embedding
Major problems of user embedding is always around the new user:

* We train a model with [latent cf + neural network](3.1.3_recommender_system.ipynb)
* Usually we won't retrain a model within the same day.
* If the new user some with his/her preference record, we have to train it in a way within the consistency of the old user's latent vector
* So we can't really apply the adavanced model to the fresh users.

The purpose of this model, is to achieve the accuracy of the forementioned model, but not depend on user embedding

In [1]:
import os
import pandas as pd
import numpy as np

Download the movielens data (yeah, I known, again)

In [2]:
# %cd /data
# !!wget http://files.grouplens.org/datasets/movielens/ml-latest-small.zip
# !!unzip ml-latest-small.zip

In [3]:
%ls /data/ml-latest-small/

README.txt   links.csv    movies.csv   ratings.csv  tags.csv

In [4]:
DATA = "/data/ml-latest-small/"
DIM = 100 # dimension for embedding
SEQ_LEN = 19

In [5]:
files = os.listdir(DATA)
files

['links.csv', 'tags.csv', 'ratings.csv', 'README.txt', 'movies.csv']

In [6]:
data = dict()
for f in files:
    if f[-3:]=="csv":
        data[f.split(".")[0]] = pd.read_csv(DATA+f)

### Check the data

In [7]:
from IPython.display import display
list(display(k,v.sample(5)) for k,v in data.items())

'links'

      movieId  imdbId   tmdbId
4938     7020  102721  14904.0
4119     5410   67756    811.0
7533    77846  118528  12219.0
7468    74630   52427  56931.0
2704     3391   94321  26827.0

'tags'

      userId  movieId        tag   timestamp
466      364    64957  Brad Pitt  1444531041
1219     547   118880  toplist14  1449757002
1244     547   134859  toplist15  1449755731
954      547     6515        tcm  1190475823
1193     547   112070       tivo  1476113970

'ratings'

       userId  movieId  rating   timestamp
68468     475    45666     4.0  1447327976
96315     642     1601     4.0   881526098
91484     607     1089     4.5  1118247427
87313     580    51255     4.0  1199493081
70822     494    34405     4.0  1342746088

'movies'

,movieId,title,genres
1268,1596,Career Girls (1997),Drama
1367,1732,"Big Lebowski, The (1998)",Comedy|Crime
3055,3822,"Girl on the Bridge, The (Fille sur le pont, La...",Drama|Romance
3703,4723,"Deep End, The (2001)",Drama
5811,26501,Choose Me (1984),Comedy|Romance

[None, None, None, None]

In [8]:
rate_df = data["ratings"]
len(rate_df)

100004

In [31]:
userId = list(set(data["ratings"]["userId"]))
movieId = list(set(data["ratings"]["movieId"]))
print("total number of users and movies:\t",len(userId),"\t",len(movieId))

total number of users and movies:	 671 	 9066

In [10]:
u2i = dict((v,k) for k,v in enumerate(userId))
m2i = dict((v,k) for k,v in enumerate(movieId))
i2u = dict((k,v) for k,v in enumerate(userId))
i2m = dict((k,v) for k,v in enumerate(movieId))

In [11]:
rate_df["movieIdx"] = rate_df.movieId.apply(lambda x:m2i[x]).astype(int)
rate_df["userIdx"] = rate_df.userId.apply(lambda x:u2i[x]).astype(int)
rate_df["rating"] = rate_df["rating"]/5

In [12]:
user_count = len(userId)
print(user_count)
valid_split = np.random.rand(user_count)>.9
train_idx = np.array(range(user_count))[~valid_split]
valid_idx = np.array(range(user_count))[valid_split]

671

In [13]:
train_df = rate_df[rate_df.userId.isin(train_idx)]
valid_df = rate_df[rate_df.userId.isin(valid_idx)]

Since user id mapping doesn't matter any more. 

It's easier to make a dataset with contineous user_id.

In [14]:
train_u2i = dict((v,k) for k,v in enumerate(set(train_df.userId)))
valid_u2i = dict((v,k) for k,v in enumerate(set(valid_df.userId)))
train_df["userId"] = train_df.userId.apply(lambda x:train_u2i[x])
valid_df["userId"] = valid_df.userId.apply(lambda x:valid_u2i[x])

/Users/salvor/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/salvor/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [15]:
def get_user_trail(rate_df):
    return rate_df.sort_values(by=["userId","timestamp"]).groupby("userId")
    #gb.apply(lambda x:x.sample(n = 20, replace = False))
gb = get_user_trail(rate_df)
train_gb = get_user_trail(train_df)
valid_gb = get_user_trail(valid_df)

In [16]:
a = gb.apply(lambda x:x.sample(n = 20, replace = False))

In [35]:
rate_df

        userId  movieId  rating   timestamp  movieIdx
0            1       31     0.5  1260759144        30
1            1     1029     0.6  1260759179       921
2            1     1061     0.6  1260759182       949
3            1     1129     0.4  1260759185      1004
4            1     1172     0.8  1260759205      1038
5            1     1263     0.4  1260759151      1126
6            1     1287     0.4  1260759187      1149
7            1     1293     0.4  1260759148      1155
8            1     1339     0.7  1260759125      1195
9            1     1343     0.4  1260759131      1199
10           1     1371     0.5  1260759135      1226
11           1     1405     0.2  1260759203      1260
12           1     1953     0.8  1260759191      1697
13           1     2105     0.8  1260759139      1849
14           1     2150     0.6  1260759194      1894
15           1     2193     0.4  1260759198      1932
16           1     2294     0.4  1260759108      2015
17           1     2455     0.5  1260759113      2169
18           1     2968     0.2  1260759200      2616
19           1     3671     0.6  1260759117      3207
20           2       10     0.8   835355493         9
21           2       17     1.0   835355681        16
22           2       39     1.0   835355604        38
23           2       47     0.8   835355552        46
24           2       50     0.8   835355586        49
25           2       52     0.6   835356031        51
26           2       62     0.6   835355749        60
27           2      110     0.8   835355532       108
28           2      144     0.6   835356016       136
29           2      150     1.0   835355395       142
...        ...      ...     ...         ...       ...
99974      671     4034     0.9  1064245493      3541
99975      671     4306     1.0  1064245548      3754
99976      671     4308     0.7  1065111985      3755
99977      671     4880     0.8  1065111973      4188
99978      671     4886     1.0  1064245488      4192
99979      671     4896     1.0  1065111996      4199
99980      671     4963     0.9  1065111855      4246
99981      671     4973     0.9  1064245471      4256
99982      671     4993     1.0  1064245483      4273
99983      671     4995     0.8  1064891537      4275
99984      671     5010     0.4  1066793004      4288
99985      671     5218     0.4  1065111990      4429
99986      671     5299     0.6  1065112004      4487
99987      671     5349     0.8  1065111863      4520
99988      671     5377     0.8  1064245557      4543
99989      671     5445     0.9  1064891627      4586
99990      671     5464     0.6  1064891549      4601
99991      671     5669     0.8  1063502711      4740
99992      671     5816     0.8  1065111963      4826
99993      671     5902     0.7  1064245507      4879
99994      671     5952     1.0  1063502716      4914
99995      671     5989     0.8  1064890625      4940
99996      671     5991     0.9  1064245387      4942
99997      671     5995     0.8  1066793014      4946
99998      671     6212     0.5  1065149436      5060
99999      671     6268     0.5  1065579370      5102
100000     671     6269     0.8  1065149201      5103
100001     671     6365     0.8  1070940363      5166
100002     671     6385     0.5  1070979663      5179
100003     671     6565     0.7  1074784724      5280

[100004 rows x 5 columns]

In [34]:
a

               userId  movieId  rating   timestamp  movieIdx
userId
1      6            1     1287     0.4  1260759187      1149
       15           1     2193     0.4  1260759198      1932
       9            1     1343     0.4  1260759131      1199
       8            1     1339     0.7  1260759125      1195
       13           1     2105     0.8  1260759139      1849
       16           1     2294     0.4  1260759108      2015
       5            1     1263     0.4  1260759151      1126
       7            1     1293     0.4  1260759148      1155
       2            1     1061     0.6  1260759182       949
       14           1     2150     0.6  1260759194      1894
       1            1     1029     0.6  1260759179       921
       17           1     2455     0.5  1260759113      2169
       0            1       31     0.5  1260759144        30
       11           1     1405     0.2  1260759203      1260
       3            1     1129     0.4  1260759185      1004
       18           1     2968     0.2  1260759200      2616
       19           1     3671     0.6  1260759117      3207
       4            1     1172     0.8  1260759205      1038
       12           1     1953     0.8  1260759191      1697
       10           1     1371     0.5  1260759135      1226
2      68           2      454     0.8   835355604       434
       20           2       10     0.8   835355493         9
       33           2      168     0.6   835355710       160
       65           2      382     0.6   835356165       369
       75           2      500     0.8   835355731       478
       60           2      367     0.6   835355619       354
       34           2      185     0.6   835355511       177
       77           2      509     0.8   835355719       487
       26           2       62     0.6   835355749        60
       27           2      110     0.8   835355532       108
...               ...      ...     ...         ...       ...
670    99886      670     2770     0.8   938781328      2444
       99884      670     2723     0.4   940944033      2404
       99871      670      593     1.0   938782234       563
       99873      670     1183     1.0   938782193      1048
       99875      670     1584     0.8   938782344      1402
       99867      670      318     1.0   938781934       305
       99876      670     1617     0.4   938781934      1433
       99880      670     2291     0.8   938782145      2012
       99865      670      110     0.6   938782093       108
       99878      670     1923     0.4   938782414      1667
671    99959      671     3160     0.6  1063503682      2788
       99986      671     5299     0.6  1065112004      4487
       99977      671     4880     0.8  1065111973      4188
       99935      671     2028     0.8  1064891584      1772
       99928      671     1610     0.8  1064891635      1426
       99981      671     4973     0.9  1064245471      4256
       100002     671     6385     0.5  1070979663      5179
       99925      671     1266     0.8  1065149270      1129
       99934      671     2011     0.7  1063500873      1755
       99931      671     1676     0.6  1065108970      1482
       99949      671     2797     0.8  1063500821      2469
       99916      671     1198     1.0  1064891024      1062
       99970      671     4019     0.7  1065111959      3527
       99926      671     1291     0.8  1064891140      1153
       99963      671     3421     0.8  1063502737      2992
       99905      671      608     0.8  1064890575       575
       99967      671     3897     0.4  1063503718      3412
       99972      671     4027     0.8  1063500993      3535
       99901      671      551     1.0  1063503908       529
       99936      671     2064     0.8  1063502750      1808

[13420 rows x 5 columns]

In [17]:
from torch.utils.data.dataset import Dataset
from torch.utils.data.dataloader import DataLoader

In [36]:
pick_k = np.array([0]*19 +[1])==1

In [38]:
def sample_split(x):
    sampled = x.sample(n = 20, replace = False)
    seq = sampled.head(19).sort_values(by="timestamp")
    y = sampled[pick_k]
    return pd.concat([seq,y])

class rnn_record(Dataset):
    def __init__(self, gb):
        self.gb = gb
        self.make_seq()
    
    def make_seq(self):
        self.all_seq = self.gb.apply(sample_split)
        
    def __len__(self):
        return len(self.gb)
        
    def __getitem__(self,idx):
        df = self.all_seq.loc[idx]
        seq = df.head(19)[["movieId","rating"]].values
        targ = df[pick_k][["movieId","rating"]].values
        targ_v, targ_y =targ[:,0], targ[:,1]
        return idx,seq,targ_v,targ_y
ds = rnn_record(gb)
train_ds = rnn_record(train_gb)
valid_ds = rnn_record(valid_gb)

In [39]:
dl = DataLoader(ds,batch_size=32,shuffle=True)
gen = iter(dl)

idx,seq,targ_v,targ_y = next(gen)

idx.size(),seq.size(),targ_v.size(),targ_y.size()

(torch.Size([32]),
 torch.Size([32, 19, 2]),
 torch.Size([32, 1]),
 torch.Size([32, 1]))

### Model

In [21]:
import torch
from torch import nn
from torch.nn import functional as F

In [33]:
class mLinkNet(nn.Module):
    def __init__(self, hidden_size,v_size):
        """
        mLinkNet, short for missing link net
        """
        super(mLinkNet,self).__init__()
        self.hidden_size = hidden_size
        self.v_size = v_size
        self.emb = nn.Embedding(v_size,hidden_size)
        
        self.rnn = nn.GRU(input_size = self.hidden_size+1,
                          hidden_size= hidden_size+1,
                          num_layers=1,
                          batch_first = True,
                          dropout=0)
        
        self.mlp = nn.Sequential(*[
            nn.Dropout(.3),
            nn.Linear(hidden_size*2 + 1, 256, bias=False),
            nn.BatchNorm1d(256),
            nn.Linear(256,1,bias=False),
            nn.Sigmoid(),
        ])
    
    def forward(self,seq,targ_v):
        seq_vec = torch.cat([self.emb(seq[:,0].long()),
                             seq[:,1].unsqueeze(-1).float()], dim=2)
        output, hn = self.rnn(seq_vec)
        x = torch.cat([hn.squeeze(0),self.emb(targ_v.long()).squeeze(1)],dim=1)
        return self.mlp(x)

In [23]:
mln = mLinkNet(hidden_size = DIM, v_size = len(movieId))

# mln(seq, targ_v)

In [24]:
from torch.optim import Adam
from ray.matchbox import Trainer
opt = Adam(mln.parameters())
loss_func = nn.MSELoss()

In [25]:
trainer = Trainer(train_ds, val_dataset=valid_ds, batch_size=16, print_on=3)

In [26]:
train_len = len(trainer.train_data)
valid_len = len(trainer.val_data)
def action(*args,**kwargs):
    # get data from data feeder
    idx,seq,targ_v,y = args[0]
    y = y.float()
    
    # Clear the Jacobian Matrix
    opt.zero_grad()
    
    # Predict y hat
    y_ = mln(seq, targ_v)
    # Calculate Loss
    loss = loss_func(y_,y)
    
    # Backward Propagation
    loss.backward()
    opt.step()
    # Mean Absolute Loss as print out metrics
    mae = torch.mean(torch.abs(y_-y))
    if kwargs["ite"] == train_len - 1: # resample the sequence
        trainer.train_data.dataset.make_seq()
    return {"loss":loss.item(),"mae":mae.item()}

def val_action(*args,**kwargs):
    """
    A validation step
    Exactly the same like train step, but no learning, only forward pass
    """
    idx,seq,targ_v,y = args[0]
    y = y.float()
    
    y_ = mln(seq, targ_v)
    
    loss = loss_func(y_,y)
    mae = torch.mean(torch.abs(y_-y))
    if kwargs["ite"] == valid_len - 1:
        trainer.val_data.dataset.make_seq()
    return {"loss":loss.item(),"mae":mae.item()}
trainer.action  = action
trainer.val_action  = val_action

In [27]:
trainer.train(50)

⭐[ep_0_i_35]	loss	0.065✨	mae	0.221: 100%|██████████| 38/38 [00:03<00:00, 11.48it/s]
😎[val_ep_0_i_4]	loss	0.069😂	mae	0.216: 100%|██████████| 5/5 [00:00<00:00, 13.04it/s]
⭐[ep_1_i_35]	loss	0.076✨	mae	0.235: 100%|██████████| 38/38 [00:03<00:00, 11.72it/s]
😎[val_ep_1_i_4]	loss	0.048😂	mae	0.178: 100%|██████████| 5/5 [00:00<00:00, 15.16it/s]
⭐[ep_2_i_35]	loss	0.058✨	mae	0.193: 100%|██████████| 38/38 [00:02<00:00, 13.42it/s]
😎[val_ep_2_i_4]	loss	0.069😂	mae	0.208: 100%|██████████| 5/5 [00:00<00:00, 15.47it/s]
⭐[ep_3_i_35]	loss	0.048✨	mae	0.160: 100%|██████████| 38/38 [00:02<00:00, 12.90it/s]
😎[val_ep_3_i_4]	loss	0.037😂	mae	0.150: 100%|██████████| 5/5 [00:00<00:00, 14.24it/s]
⭐[ep_4_i_35]	loss	0.048✨	mae	0.168: 100%|██████████| 38/38 [00:02<00:00, 13.37it/s]
😎[val_ep_4_i_4]	loss	0.033😂	mae	0.146: 100%|██████████| 5/5 [00:00<00:00, 15.08it/s]
⭐[ep_5_i_35]	loss	0.036✨	mae	0.146: 100%|██████████| 38/38 [00:02<00:00, 13.11it/s]
😎[val_ep_5_i_4]	loss	0.058😂	mae	0.184: 100%|██████████| 5/5 [00:00<00:00, 14.00it/s]
⭐[ep_6_i_35]	loss	0.097✨	mae	0.227: 100%|██████████| 38/38 [00:02<00:00, 12.95it/s]
😎[val_ep_6_i_4]	loss	0.069😂	mae	0.208: 100%|██████████| 5/5 [00:00<00:00, 14.84it/s]
⭐[ep_7_i_35]	loss	0.052✨	mae	0.201: 100%|██████████| 38/38 [00:02<00:00, 12.94it/s]
😎[val_ep_7_i_4]	loss	0.047😂	mae	0.161: 100%|██████████| 5/5 [00:00<00:00, 14.83it/s]
⭐[ep_8_i_35]	loss	0.051✨	mae	0.178: 100%|██████████| 38/38 [00:02<00:00, 12.93it/s]
😎[val_ep_8_i_4]	loss	0.035😂	mae	0.160: 100%|██████████| 5/5 [00:00<00:00, 16.48it/s]
⭐[ep_9_i_35]	loss	0.043✨	mae	0.166: 100%|██████████| 38/38 [00:02<00:00, 13.21it/s]
😎[val_ep_9_i_4]	loss	0.031😂	mae	0.132: 100%|██████████| 5/5 [00:00<00:00, 15.45it/s]
⭐[ep_10_i_35]	loss	0.038✨	mae	0.156: 100%|██████████| 38/38 [00:02<00:00, 13.31it/s]
😎[val_ep_10_i_4]	loss	0.039😂	mae	0.150: 100%|██████████| 5/5 [00:00<00:00, 13.33it/s]
⭐[ep_11_i_35]	loss	0.060✨	mae	0.199: 100%|██████████| 38/38 [00:02<00:00, 12.85it/s]
😎[val_ep_11_i_4]	loss	0.036😂	mae	0.147: 100%|██████████| 5/5 [00:00<00:00, 15.87it/s]
⭐[ep_12_i_35]	loss	0.036✨	mae	0.146: 100%|██████████| 38/38 [00:02<00:00, 13.91it/s]
😎[val_ep_12_i_4]	loss	0.037😂	mae	0.145: 100%|██████████| 5/5 [00:00<00:00, 15.37it/s]
⭐[ep_13_i_35]	loss	0.040✨	mae	0.158: 100%|██████████| 38/38 [00:02<00:00, 13.59it/s]
😎[val_ep_13_i_4]	loss	0.062😂	mae	0.196: 100%|██████████| 5/5 [00:00<00:00, 16.58it/s]
⭐[ep_14_i_35]	loss	0.037✨	mae	0.152: 100%|██████████| 38/38 [00:02<00:00, 12.79it/s]
😎[val_ep_14_i_4]	loss	0.039😂	mae	0.147: 100%|██████████| 5/5 [00:00<00:00, 14.38it/s]
⭐[ep_15_i_35]	loss	0.032✨	mae	0.144: 100%|██████████| 38/38 [00:02<00:00, 13.93it/s]
😎[val_ep_15_i_4]	loss	0.049😂	mae	0.169: 100%|██████████| 5/5 [00:00<00:00, 16.12it/s]
⭐[ep_16_i_35]	loss	0.076✨	mae	0.224: 100%|██████████| 38/38 [00:02<00:00, 13.69it/s]
😎[val_ep_16_i_4]	loss	0.042😂	mae	0.159: 100%|██████████| 5/5 [00:00<00:00, 15.60it/s]
⭐[ep_17_i_35]	loss	0.036✨	mae	0.155: 100%|██████████| 38/38 [00:02<00:00, 13.55it/s]
😎[val_ep_17_i_4]	loss	0.040😂	mae	0.161: 100%|██████████| 5/5 [00:00<00:00, 15.66it/s]
⭐[ep_18_i_35]	loss	0.032✨	mae	0.150: 100%|██████████| 38/38 [00:02<00:00, 13.72it/s]
😎[val_ep_18_i_4]	loss	0.037😂	mae	0.148: 100%|██████████| 5/5 [00:00<00:00, 15.12it/s]
⭐[ep_19_i_35]	loss	0.045✨	mae	0.162: 100%|██████████| 38/38 [00:02<00:00, 13.51it/s]
😎[val_ep_19_i_4]	loss	0.042😂	mae	0.170: 100%|██████████| 5/5 [00:00<00:00, 15.61it/s]
⭐[ep_20_i_35]	loss	0.048✨	mae	0.165: 100%|██████████| 38/38 [00:02<00:00, 13.20it/s]
😎[val_ep_20_i_4]	loss	0.035😂	mae	0.143: 100%|██████████| 5/5 [00:00<00:00, 18.53it/s]
⭐[ep_21_i_35]	loss	0.053✨	mae	0.190: 100%|██████████| 38/38 [00:02<00:00, 12.74it/s]
😎[val_ep_21_i_4]	loss	0.034😂	mae	0.149: 100%|██████████| 5/5 [00:00<00:00, 15.70it/s]
⭐[ep_22_i_35]	loss	0.061✨	mae	0.191: 100%|██████████| 38/38 [00:02<00:00, 13.23it/s]
😎[val_ep_22_i_4]	loss	0.050😂	mae	0.176: 100%|██████████| 5/5 [00:00<00:00, 12.91it/s]
⭐[ep_23_i_35]	loss	0.038✨	mae	0.169: 100%|██████████| 38/38 [00:03<00:00, 11.84it/s]
😎[val_ep_23_i_4]	loss	0.044😂	mae	0.163: 100%|██████████| 5/5 [00:00<00:00, 13.41it/s]
⭐[ep_24_i_35]	loss	0.032✨	mae	0.141: 100%|██████████| 38/38 [00:03<00:00, 10.52it/s]
😎[val_ep_24_i_4]	loss	0.034😂	mae	0.151: 100%|██████████| 5/5 [00:00<00:00, 13.65it/s]
⭐[ep_25_i_35]	loss	0.027✨	mae	0.120: 100%|██████████| 38/38 [00:03<00:00, 10.49it/s]
😎[val_ep_25_i_4]	loss	0.043😂	mae	0.165: 100%|██████████| 5/5 [00:00<00:00, 15.35it/s]
⭐[ep_26_i_35]	loss	0.040✨	mae	0.169: 100%|██████████| 38/38 [00:03<00:00, 11.44it/s]
😎[val_ep_26_i_4]	loss	0.038😂	mae	0.154: 100%|██████████| 5/5 [00:00<00:00, 14.57it/s]
⭐[ep_27_i_35]	loss	0.038✨	mae	0.155: 100%|██████████| 38/38 [00:03<00:00, 11.13it/s]
😎[val_ep_27_i_4]	loss	0.050😂	mae	0.171: 100%|██████████| 5/5 [00:00<00:00, 13.50it/s]
⭐[ep_28_i_35]	loss	0.050✨	mae	0.170: 100%|██████████| 38/38 [00:03<00:00, 10.70it/s]
😎[val_ep_28_i_4]	loss	0.048😂	mae	0.166: 100%|██████████| 5/5 [00:00<00:00, 14.13it/s]
⭐[ep_29_i_35]	loss	0.054✨	mae	0.175: 100%|██████████| 38/38 [00:03<00:00, 11.40it/s]
😎[val_ep_29_i_4]	loss	0.047😂	mae	0.165: 100%|██████████| 5/5 [00:00<00:00, 14.46it/s]
⭐[ep_30_i_35]	loss	0.059✨	mae	0.187: 100%|██████████| 38/38 [00:03<00:00, 10.95it/s]
😎[val_ep_30_i_4]	loss	0.023😂	mae	0.125: 100%|██████████| 5/5 [00:00<00:00, 12.71it/s]
⭐[ep_31_i_35]	loss	0.046✨	mae	0.180: 100%|██████████| 38/38 [00:03<00:00, 10.17it/s]
😎[val_ep_31_i_4]	loss	0.035😂	mae	0.149: 100%|██████████| 5/5 [00:00<00:00, 13.13it/s]
⭐[ep_32_i_35]	loss	0.046✨	mae	0.180: 100%|██████████| 38/38 [00:03<00:00, 10.97it/s]
😎[val_ep_32_i_4]	loss	0.055😂	mae	0.180: 100%|██████████| 5/5 [00:00<00:00, 15.06it/s]
⭐[ep_33_i_35]	loss	0.052✨	mae	0.194: 100%|██████████| 38/38 [00:03<00:00, 10.96it/s]
😎[val_ep_33_i_4]	loss	0.044😂	mae	0.154: 100%|██████████| 5/5 [00:00<00:00, 14.37it/s]
⭐[ep_34_i_35]	loss	0.067✨	mae	0.194: 100%|██████████| 38/38 [00:03<00:00, 11.43it/s]
😎[val_ep_34_i_4]	loss	0.044😂	mae	0.172: 100%|██████████| 5/5 [00:00<00:00, 15.83it/s]
⭐[ep_35_i_35]	loss	0.070✨	mae	0.206: 100%|██████████| 38/38 [00:03<00:00, 12.16it/s]
😎[val_ep_35_i_4]	loss	0.044😂	mae	0.164: 100%|██████████| 5/5 [00:00<00:00, 15.52it/s]
⭐[ep_36_i_35]	loss	0.043✨	mae	0.168: 100%|██████████| 38/38 [00:03<00:00, 12.64it/s]
😎[val_ep_36_i_4]	loss	0.030😂	mae	0.142: 100%|██████████| 5/5 [00:00<00:00, 15.53it/s]
⭐[ep_37_i_35]	loss	0.046✨	mae	0.176: 100%|██████████| 38/38 [00:03<00:00, 12.18it/s]
😎[val_ep_37_i_4]	loss	0.043😂	mae	0.166: 100%|██████████| 5/5 [00:00<00:00, 15.50it/s]
⭐[ep_38_i_35]	loss	0.043✨	mae	0.174: 100%|██████████| 38/38 [00:03<00:00, 12.28it/s]
😎[val_ep_38_i_4]	loss	0.033😂	mae	0.131: 100%|██████████| 5/5 [00:00<00:00, 14.84it/s]
⭐[ep_39_i_35]	loss	0.035✨	mae	0.152: 100%|██████████| 38/38 [00:03<00:00, 11.21it/s]
😎[val_ep_39_i_4]	loss	0.049😂	mae	0.162: 100%|██████████| 5/5 [00:00<00:00, 15.26it/s]
⭐[ep_40_i_35]	loss	0.048✨	mae	0.176: 100%|██████████| 38/38 [00:03<00:00, 11.54it/s]
😎[val_ep_40_i_4]	loss	0.043😂	mae	0.171: 100%|██████████| 5/5 [00:00<00:00, 16.06it/s]
⭐[ep_41_i_35]	loss	0.038✨	mae	0.162: 100%|██████████| 38/38 [00:03<00:00, 12.12it/s]
😎[val_ep_41_i_4]	loss	0.036😂	mae	0.145: 100%|██████████| 5/5 [00:00<00:00, 16.10it/s]
⭐[ep_42_i_35]	loss	0.034✨	mae	0.152: 100%|██████████| 38/38 [00:03<00:00, 11.89it/s]
😎[val_ep_42_i_4]	loss	0.031😂	mae	0.136: 100%|██████████| 5/5 [00:00<00:00, 16.16it/s]
⭐[ep_43_i_35]	loss	0.035✨	mae	0.154: 100%|██████████| 38/38 [00:03<00:00, 11.97it/s]
😎[val_ep_43_i_4]	loss	0.067😂	mae	0.200: 100%|██████████| 5/5 [00:00<00:00, 16.56it/s]
⭐[ep_44_i_35]	loss	0.044✨	mae	0.171: 100%|██████████| 38/38 [00:03<00:00, 11.54it/s]
😎[val_ep_44_i_4]	loss	0.052😂	mae	0.187: 100%|██████████| 5/5 [00:00<00:00, 15.84it/s]
⭐[ep_45_i_35]	loss	0.046✨	mae	0.165: 100%|██████████| 38/38 [00:03<00:00, 10.30it/s]
😎[val_ep_45_i_4]	loss	0.042😂	mae	0.166: 100%|██████████| 5/5 [00:00<00:00, 11.65it/s]
⭐[ep_46_i_35]	loss	0.041✨	mae	0.165: 100%|██████████| 38/38 [00:03<00:00, 11.18it/s]
😎[val_ep_46_i_4]	loss	0.044😂	mae	0.177: 100%|██████████| 5/5 [00:00<00:00, 15.93it/s]

⭐[ep_47_i_35]	loss	0.046✨	mae	0.177: 100%|██████████| 38/38 [00:03<00:00, 12.00it/s]
😎[val_ep_47_i_4]	loss	0.032😂	mae	0.153: 100%|██████████| 5/5 [00:00<00:00, 15.63it/s]
⭐[ep_48_i_35]	loss	0.061✨	mae	0.199: 100%|██████████| 38/38 [00:03<00:00, 11.86it/s]
😎[val_ep_48_i_4]	loss	0.046😂	mae	0.168: 100%|██████████| 5/5 [00:00<00:00, 15.95it/s]
⭐[ep_49_i_35]	loss	0.038✨	mae	0.170: 100%|██████████| 38/38 [00:03<00:00, 12.00it/s]
😎[val_ep_49_i_4]	loss	0.030😂	mae	0.142: 100%|██████████| 5/5 [00:00<00:00, 15.60it/s]